# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 734d85e09e822abd2476a2bececa396892369ceb45e8309226c8511960c5f65f80a18f40d1319172f27917a1d7050c41edf0bd34f8ffc885eb92b2ce6fb46580

test:
  secret_key_base: b0fa7fdeab46f8ad682054107a2568a5ed9126a269b43240dd237e230dc1d07aea4f61ea5d21175a959909610c311ae5b85dca0bf47b15faf2dc36eb97a3b45e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
